# Generated by Django 3.0.3 on 2020-03-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbconvert', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classificacao',
            name='cod_secao',
        ),
        migrations.RemoveField(
            model_name='classificacao',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='Tamanho',
        ),
        migrations.DeleteModel(
            name='Sortemp',
        ),
        migrations.DeleteModel(
            name='Sortim',
        ),
        migrations.DeleteModel(
            name='Cruzada',
        ),
        migrations.DeleteModel(
            name='Classificacao',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.DeleteModel(
            name='Secao',
        ),
        migrations.DeleteModel(
            name='Tamanhos',
        ),
    ]
