# Generated by Django 3.0.3 on 2020-03-20 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbconvert', '0002_auto_20200320_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cruzada',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Cod_sortimento', models.CharField(blank=True, max_length=255, null=True)),
                ('Cod_mercadoria', models.CharField(blank=True, max_length=255, null=True)),
                ('Desc_mercadoria', models.CharField(blank=True, max_length=255, null=True)),
                ('Prioridade', models.CharField(blank=True, max_length=255, null=True)),
                ('Voltagem_item', models.CharField(blank=True, max_length=255, null=True)),
                ('Voltagem_filial', models.CharField(blank=True, max_length=255, null=True)),
                ('Vigencia_inicio', models.DateField(blank=True, null=True)),
                ('Vigencia_fim', models.DateField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=2, null=True)),
                ('Filial', models.IntegerField(blank=True, null=True)),
                ('Cod_Secao', models.IntegerField(blank=True, null=True)),
                ('Desc_Secao', models.CharField(blank=True, max_length=255, null=True)),
                ('Cod_Tamanho', models.CharField(blank=True, max_length=255, null=True)),
                ('Desc_Tamanho', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cruzada',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('Cod_secao', models.IntegerField(primary_key=True, serialize=False)),
                ('Descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sortemp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Cod_sortimento', models.CharField(blank=True, max_length=255, null=True)),
                ('Cod_secao', models.CharField(blank=True, max_length=255, null=True)),
                ('Desc_secao', models.CharField(blank=True, max_length=255, null=True)),
                ('Cod_tamanho', models.CharField(blank=True, max_length=255, null=True)),
                ('Desc_tamanho', models.CharField(blank=True, max_length=255, null=True)),
                ('Cod_publico', models.CharField(blank=True, max_length=255, null=True)),
                ('Desc_publico', models.CharField(blank=True, max_length=255, null=True)),
                ('Cod_mercadoria', models.CharField(blank=True, max_length=255, null=True)),
                ('Desc_mercadoria', models.CharField(blank=True, max_length=255, null=True)),
                ('Merc_conj', models.CharField(blank=True, max_length=255, null=True)),
                ('Prioridade', models.CharField(blank=True, max_length=255, null=True)),
                ('Qtde', models.CharField(blank=True, max_length=255, null=True)),
                ('Voltagem', models.CharField(blank=True, max_length=255, null=True)),
                ('Vigencia_inicio', models.DateField(blank=True, null=True)),
                ('Vigencia_fim', models.DateField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=2, null=True)),
                ('Setor', models.CharField(blank=True, max_length=255, null=True)),
                ('Desc_setor', models.CharField(blank=True, max_length=255, null=True)),
                ('Classe', models.CharField(blank=True, max_length=255, null=True)),
                ('Desc_classe', models.CharField(blank=True, max_length=255, null=True)),
                ('Especie', models.CharField(blank=True, max_length=255, null=True)),
                ('Desc_especie', models.CharField(blank=True, max_length=255, null=True)),
                ('Marca', models.CharField(blank=True, max_length=255, null=True)),
                ('Desc_marca', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sortim',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('Filial', models.CharField(blank=True, max_length=255, null=True)),
                ('Voltagem', models.CharField(blank=True, max_length=255, null=True)),
                ('Cod_Publico', models.CharField(blank=True, max_length=255, null=True)),
                ('Desc_Publico', models.CharField(blank=True, max_length=255, null=True)),
                ('Cod_Secao', models.CharField(blank=True, max_length=255, null=True)),
                ('Desc_Secao', models.CharField(blank=True, max_length=255, null=True)),
                ('Cod_Sortimento', models.CharField(blank=True, max_length=255, null=True)),
                ('Cod_Tamanho', models.CharField(blank=True, max_length=255, null=True)),
                ('Desc_Tamanho', models.CharField(blank=True, max_length=255, null=True)),
                ('Tipo_Publico', models.CharField(blank=True, max_length=255, null=True)),
                ('Solic_Volt_Dif', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tamanhos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tamanho', models.CharField(max_length=20)),
                ('Tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Tamanho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbconvert.Tamanhos')),
            ],
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantidade', models.IntegerField()),
                ('cod_secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbconvert.Secao')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbconvert.Perfil')),
            ],
        ),
    ]
